### ISSUE TITLE
review

### ISSUE THREAD

**Issue by ale-strada** [leandromartin114/dwf-m9-e-commerce-backend#1]
Hola @leandromartin114. Felicitaciones, quedo muy bien la API. Probe los endpoints y funcionan todos. Solo me quedo la duda con uno, que es el "Me/update one data". En este solo pude cambiar la propiedad address, no se si yo le mande mal el body o le falta algo.

**Comment by leandromartin114** [comment]
Hola Ale, gracias por la devolución! Si, en realidad ese endpoint solo permite modificar address, email y fullName que son los campos del user. Para esto, el endpoint cambia y sería api/me/address (cambia la dirección), api/me/email (modifica el email), o api/me/fullName (para cambiar el nombre). El body es siempre el mismo y en "content" va el valor por el cual se pretende modificar dicho campo. Por ejemplo, api/me/email y en body {content: nuevoemail@mail.com}. Gracias!
Saludos.

**Comment by ale-strada** [comment]
Ahh.. imaginé que había algo así.. está bueno hacerlo así..  te robo la idea para futuros trabajos jajaja saludos!

**Comment by leandromartin114** [comment]
Robe nomás! jajaja Abrazo!
